version: "3"

services:

  ml:
    image: ml
    restart: always
    deploy:
      replicas: 1
    depends_on:
      - db
    environment:
      - development=True
    ports:
    - "8888:8888"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users/jneto/dev:/users/mluser/dev
      - /Users/jneto/data:/users/mluser/data
    command: /bin/bash scripts/ju.sh
    networks:
      - testnet

#   db:
#     image: postgres
#     restart: always
#     deploy:
#       replicas: 1
#     environment:
#       - POSTGRES_DB=postgres
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=rootroot
#       - PGDATA=/var/lib/postgresql/data
#       # - PGDATA=/var/lib/postgresql/data/pgdata
#     ports:
#       - "5433:5432"
#     volumes:
#       - ml-db-pg:/var/lib/postgresql/data
#     deploy:
#       placement:
#         constraints: [node.role == manager]
#     networks:
#       - testnet
    
# volumes:
#   ml-db-pg:
#     external: true
      
networks:
  testnet:
