
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/env.ipynb

import os
from pathlib import Path
from dotenv import load_dotenv;
import yaml

def find_yml():
    config_path = os.getenv('CONFIG_PATH')
    if config_path is not None:
        p = Path(config_path) / '.Config.yml'
        if p.exists():
            return p
    dirs = ['.', '/app', '~']
    for e in dirs:
        p = Path(e) / '.Config.yml'
        if p.exists():
            return p
    return None

def Config_load():
    load_dotenv()
    fname = find_yml()
    if fname is None:
        return None
    with open(str(fname), 'r') as stream:
        try:
            Config = yaml.safe_load(stream)
        except yaml.YAMLError as exc:
            return None
    return Config

Config = Config_load()

def get_db_url(with_db_name=True):
    if Config is None:
        return None
    if not 'db' in Config:
        return None
    if os.getenv('development') is None:
        if not 'host' in Config['db']:
            return None
        host = Config['db']['host']
    else:
        if not 'host_dev' in Config['db']:
            return None
        host = Config['db']['host_dev']
    if not 'port' in Config['db']:
        port = 3306
    else:
        port = Config['db']['port']
    if not 'name' in Config['db']:
        return None
    name = Config['db']['name']
    if not 'passwd' in Config['db']:
        return None
    passwd = Config['db']['passwd']
    url = f'mysql+pymysql://root:{passwd}@{host}:{port}'
    if with_db_name:
        url = f'{url}/{name}'
    return url

def get_rest_url():
    if Config is None:
        return None
    if not 'rest' in Config:
        return None
    if os.getenv('development') is None:
        if not 'host' in Config['rest']:
            return None
        host = Config['rest']['host']
    else:
        if not 'host_dev' in Config['rest']:
            return None
        host = Config['db']['host_dev']
    if not 'port' in Config['rest']:
        return None
    port = Config['rest']['port']
    url = f'{host}:{port}'
    return url