name: ml
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - requests 
  - bcrypt
  - yaml
  - boto3
  - feather-format
  - xlsxwriter
  - matplotlib
  - seaborn
  - scikit-learn
  - openpyxl
  - python-dotenv
  - pip:
    - nest_asyncio
    - starlette-jwt
    - asyncpg
    - psycopg2-binary
    - pika
    - aio_pika
    - redis
    - awscli
    - twilio
    - sendgrid
    - xlrd
    - xlwt
    - schedule
    - aiohttp
    - uvicorn
    - starlette
    - jupyter_contrib_nbextensions
    - fire
    - feather-format