name: ml
channels:
  - conda-forge
  - anaconda
  - pytorch
  - fastai
dependencies:
  - python>=3.7
  - pip
  - anaconda
  - pytorch
  - torchvision
  - cudatoolkit=10.0
  - jupyter_contrib_nbextensions
  - matplotlib
  - feather-format
  - requests
  - uvicorn
  - starlette
  - awscli
  - fire
  - nbformat
  - sqlalchemy
  - pymysql
  - boto3
  - bcrypt
  - opencv
  - librosa
  - python-dotenv
  - yaml
  - xlsxwriter
  - fastprogress
  - pip:
    - awscli
    - twilio
    - starlette-jwt
    - asyncpg
    - pika
    - aio_pika
    - redis
    - nest_asyncio
    - xlrd
    - xlwt
    - seaborn
