name: ml
dependencies:
  - pip
  - requests 
  - uvicorn
  - starlette
  - bcrypt
  - python-dotenv
  - yaml
  - fire
  - boto3
  - feather-format
  - jupyter_contrib_nbextensions
  - xlsxwriter
  - matplotlib
  - seaborn
  - scikit-learn
  - openpyxl
  - pip:
    - nest_asyncio
    - starlette-jwt
    - asyncpg
    - psycopg2-binary
    - pika
    - aio_pika
    - redis
    - awscli
    - twilio
    - sendgrid
    - xlrd
    - xlwt
    - schedule
    - aiohttp